#Kita gunakan web server Ninx sebagai base iamage
FROM nginx:alpine

#Kita copy folder compro ke dalam folder /usr/share/nginx/html
COPY index.html /usr/share/nginx/html

#Kita expose port 80
EXPOSE 80
